title: Bills Pet Cremation Services
email: BillPet@BillPet.com
description: >- # this means to ignore newlines until "baseurl:"
  Serving the Coastal Bend and South Texas
baseurl: "" # the subpath of your site, e.g. /blog
url:

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .idea
  - local
  - tmp
  - .jekyll-cache/
#   - .sass-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
